### ISSUE TITLE
missing strings

### ISSUE THREAD

**Issue by danmarsden** [stewa75/moodle-format_easycollapsible#11]
Please make sure that during development you have debugging level set to "developer" and display errors == on.

when I add a new course and set it to use the collapsible format I get a lot of missing string errors:

here are some of the examples:
Help title string does not exist: [collapsefirst, format_easycollapsible]
Help title string does not exist: [collapsesecond, format_easycollapsible]
Help title string does not exist: [collapslast, format_easycollapsible]

Please turn debugging on and reproduce these yourself so that you make sure all of them are fixed.

**Comment by stewa75** [comment]
Done
