### ISSUE TITLE
undefined property errors when viewing course

### ISSUE THREAD

**Issue by danmarsden** [stewa75/moodle-format_easycollapsible#13]
Notice: Undefined property: stdClass::$numsections in moodle/course/format/easycollapsible/format.php on line 50
Notice: Undefined property: stdClass::$coursedisplay in moodle/course/format/easycollapsible/renderer.php on line 281

**Comment by danmarsden** [comment]
you should catch these if you have debugging set to "developer" and display errors == on in Moodle.

**Comment by stewa75** [comment]
I can reproduce the errors but I really don't know how to solve them. They seem to regard Moodle native code. Any suggestions?
