### ISSUE TITLE
Incorrect repository name

### ISSUE THREAD

**Issue by danmarsden** [stewa75/moodle-format_easycollapsible#2]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

"easycollapsible" should be renamed to "moodle-format_easycollapsible"

**Comment by stewa75** [comment]
Done
