### ISSUE TITLE
custom css not defined correctly.

### ISSUE THREAD

**Issue by danmarsden** [stewa75/moodle-format_easycollapsible#5]
styles.css should sit in the root of your plugin directory - css is collected centrally and cached by Moodle (another big performance gain.)

but make sure your css is specific enough - you should probably be prefixing all your styles with:
.format-easycollapsible

see single activity in core as an example:
https://github.com/moodle/moodle/blob/master/course/format/singleactivity/styles.css

Also format_onetopic which is a bit more detailed:
https://github.com/davidherney/moodle-format_onetopic/blob/master/styles.css

for more info on css in Moodle see:
https://docs.moodle.org/dev/CSS_Coding_Style#File_naming

**Comment by stewa75** [comment]
Done

**Comment by danmarsden** [comment]
I see you've moved this file , but haven't made it comply with our standard guidelines and it is not specific enough - eg:

section .side.right, .section .side.left

could overwrite other things incorrectly and should be prefixed with .format-easycollapsible.

also it's named incorrectly. - it should be called "styles.css" which will make it cached and included automatically - so you also would remove it being called here:
https://github.com/stewa75/moodle-format_easycollapsible/blob/4dca06f44b16f251c6ec7f4bfd3b392d0df80466/renderer.php#L57

please go back and read the docs I linked above for more information on this.

**Comment by stewa75** [comment]
Ok, sorry I didn't understand all classes names had to be modified. Now I hope they are right

**Comment by danmarsden** [comment]
no worries - you're getting closer! :-)

you don't need this line here:
https://github.com/stewa75/moodle-format_easycollapsible/blob/c2c014d870e603241d59fd403b873a0d1d09bd28/renderer.php#L57

Moodle collects all styles.css files within plugins and caches them as a single css file and gives that file to the browser "once" rather than loading it on every page load.

**Comment by stewa75** [comment]
Ok!!! Thank you, finally got it.
