### ISSUE TITLE
Consider adding travis-ci support.

### ISSUE THREAD

**Issue by danmarsden** [stewa75/moodle-format_easycollapsible#6]
Some of the tests run by the Moodle.org plugins db can be run via travis-ci on each commit in your github repo. Enabling Travis integration helps you to make sure future changes to your plugin will continue to follow the guidelines.

More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version:
grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/main/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/profile/YOUR_GITHUB_USERNAME
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has this line:

env:
global:

MOODLE_BRANCH=MOODLE_38_STABLE
you might want to add other branches to that list - so you might want to change it something like:

env:
global:
MOODLE_BRANCH=MOODLE_35_STABLE
MOODLE_BRANCH=MOODLE_36_STABLE
MOODLE_BRANCH=MOODLE_37_STABLE

**Comment by danmarsden** [comment]
to see the errors from the code pre-checks in the plugins click on the links under code prechecks on this page:
https://moodle.org/plugins/pluginversion.php?id=22028

note that fixing those all is not a requirement for approval in the plugins db, but it does improve the quality of your code.

**Comment by danmarsden** [comment]
I see you've closed this but haven't actually completed it? - can you please re-open or fix this?

**Comment by stewa75** [comment]
Not sure I have caught all your advices, hope I did. Let me know. 
I'm not so familiar with Git too so I really don't understand if now I have to close the topic or not. I try to close it, pardon me if it was a mistake.

**Comment by danmarsden** [comment]
you're getting really close! :-) - I can see the file in your repo, but the travis integration hasn't been "enabled" quite yet.

try going here:
https://travis-ci.org/account/repositories

login with your github account and sync all your repos across and you should be able to flick the switch on the moodle-format_easycollapsibile repo - once you've got that turned on, add a new commit to your github repo (something simple like changing the text in your readme and commit) then it should "trigger" the travis ci build and you'll get a report a bit like this:
https://travis-ci.org/github/danmarsden/moodle-mod_attendance/jobs/715017419

**Comment by stewa75** [comment]
Ok! Hope I have done everything right. Could you check it please?

**Comment by danmarsden** [comment]
yeah that looks like it's running now! - good work! - now take a look at the errors it reports (click on the red cross beside your recent commits in github here)
you can see all the builds are failing at the moment and it would be good to fix some of those issues up. In particular I see a PHP Lint error which is probably a blocker for plugins db approval - some of the other ones are definitely less important, but keep an eye on the ones that return an "error"  (violations and warnings are less important.)

**Comment by stewa75** [comment]
Hello Dan,
I have done my best to try to solve all the problems in the code of my plugin but I really don't know how to solve:
"The command "moodle-plugin-ci phpdoc" exited with 1. " 
I think that this is the cause why my plugin doesn't pass the travis test.
Can you help me?
I don't even found a way to re submit the new 1.8 version to your attention

Thank you so much

Stefano

**Comment by danmarsden** [comment]
wow - nice work!!
firstly - phpdoc compliance is not a requirement for inclusion in the plugins db, so you don't have to fix that, but it is nice having a green "badge" that shows it passes the tests :-)

There are 2 plugins you can install locally on your machine to help with this as well:
this one helps with phpdoc tests like the ones that are currently failing for you:
https://moodle.org/plugins/local_moodlecheck

This one runs the other code compliance checks:
https://moodle.org/plugins/local_codechecker

And depending on what IDE you use for development you might want to look here to setup your IDE to do some of this work for you as well:
https://docs.moodle.org/dev/Setting_up_development_environment#IDE 
and some other links here too:
https://docs.moodle.org/dev/Linting#Linting_in_your_editor

but in terms of the specific failures -:
* File-level phpdocs block is not found - refers to this line:
https://github.com/stewa75/moodle-format_easycollapsible/blob/master/lib.php#L16
which has a /* instead of a /** and should probably have an extra line return between the gpl thing and the file level code block.

* Class format_easycollapsible is not documented
refers to the class not having any docs - take a look at this example:
https://github.com/moodle/moodle/blob/master/course/format/topics/lib.php#L31
you can see some comments that describe the class and also package/copyright and license lines.

hopefully combining the use of the local_moodlecheck plugin and existing code examples you might be able to work out the other ones, but let me know if there's anything else that isn't clear. Good luck! :-)

in terms of uploading a new version to the plugins db - hit the "developer zone" tab and then "add a new version" button.

hope that helps!

**Comment by stewa75** [comment]
Hi Den,

thank you so much for your support!
I've done my best to follow all your advices and I've also installed the plugins but while the local_codechecker works, the other one is too old and my Moodle rejects it. I've completed all the tasks proposed by the one which works but I have the red color yet.
I really don't know what to do to have the green and I don't understand if my plugin is going to be added to the plugin db or if it stopped here.

Thank you
Stefano

**Comment by danmarsden** [comment]
looks like no one has updated the plugins db version of local_moodlecheck for a while... grab the moodlecheck plugin directly from the github repo instead like it states in the description on the plugins db:
https://github.com/moodlehq/moodle-local_moodlecheck

as mentioned - this isn't a blocker for approval in the plugins db - you don't have to fix these but it's nice to have!

We'll get to reviewing your updated code soon - just make sure if you make any more improvements while you're waiting that you update the plugins db version as well, so we are reviewing your latest code!

thanks,

**Comment by danmarsden** [comment]
not sure if you've seen... but since we created this, Travis-ci is not free anymore :-( - most people have been moving to using github actions instead.

Closing this one off.
