### ISSUE TITLE
please use core fontawesome and jquery instead of external sources

### ISSUE THREAD

**Issue by danmarsden** [stewa75/moodle-format_easycollapsible#7]
https://github.com/stewa75/easycollapsible/blob/master/renderer.php#L49

you should be able to do stuff like this to include the jquery stuff

$PAGE->requires->jquery();

and there's probably a better way to include fontawesome css from core if it isn't loaded already:

**Comment by danmarsden** [comment]
some sites will sit within an intranet and will not have external access, so loading from core lib also improves the number of places where your plugin could be used.

**Comment by stewa75** [comment]
I can't find a way to include fontawesome from core....
